// <auto-generated />
using DriveOps.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriveOps.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250705160624_AddBaseMigration")]
    partial class AddBaseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DriveOps.Models.Vehicle", b =>
                {
                    b.Property<string>("ChassisSeries")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ChassisNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ChassisSeries", "ChassisNumber");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DriveOps.Models.Bus", b =>
                {
                    b.HasBaseType("DriveOps.Models.Vehicle");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("DriveOps.Models.Car", b =>
                {
                    b.HasBaseType("DriveOps.Models.Vehicle");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("DriveOps.Models.Truck", b =>
                {
                    b.HasBaseType("DriveOps.Models.Vehicle");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("DriveOps.Models.Vehicle", b =>
                {
                    b.OwnsOne("DriveOps.Domain.ValueObjects.ChassisId", "ChassisId", b1 =>
                        {
                            b1.Property<string>("VehicleChassisSeries")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<long>("VehicleChassisNumber")
                                .HasColumnType("bigint");

                            b1.Property<long>("Number")
                                .HasColumnType("bigint");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VehicleChassisSeries", "VehicleChassisNumber");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleChassisSeries", "VehicleChassisNumber");
                        });

                    b.Navigation("ChassisId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
